apiVersion: v1
kind: ConfigMap
metadata:
  name: yoyoyo
  labels:
    app: conjhgygf
data:
  LangUsed: |-
   {{- range .Values.LangUsed }}
    - {{ . | title }}
   {{- end }}
  CodingLangs: |-
   {{- range $index, $langs := .Values.LangUsed }}
    - {{ $index }} : {{ $langs }}
   {{- end}}
